# make classification list.

library('data.table')
library('stringr')
library("readxl")
library("writexl")

cosmo_class<-data.table(read_excel('raw/20220526_cosmo_classify/Upwork service desciptions - COMPLETE.xlsx'))
cosmo_update<-data.table(read_excel('raw/20220526_cosmo_classify/check_cosmo - COMPLETE (3).xlsx'))
cosmo_class<-rbind(cosmo_class[!(raw_id%in% cosmo_update$raw_id)], cosmo_update)
stopifnot(nrow(cosmo_class)==uniqueN(cosmo_class$raw_id))

orig_vars<-copy(colnames(cosmo_class))
cosmo_class[, `Service Description`:=ifelse(substring(`Service Description`,1,1)=="'",substring(`Service Description`,2),`Service Description`)]

# how many marks per column
cosmo_class[, marked:=0]
for (var in colnames(cosmo_class)[!(colnames(cosmo_class) %in% c("Service Description", "raw_id", "marked")) ]) {
  cosmo_class[, marked:=marked+!is.na(get(var))]
}
table(cosmo_class$marked)

# how many in the main categories.
cosmo_class[, main_cat:=0]
for (var in colnames(cosmo_class)[4:16]) {
  cosmo_class[, main_cat:=marked+!is.na(get(var))]
}
table(cosmo_class$main_cat)
cosmo_class[, main_cat:=ifelse(main_cat>1, main_cat-!is.na(`Admin/Consult`),main_cat)]
table(cosmo_class$main_cat)

### generate task categories - use groupings generated by cosmetologist.
cosmo_class[Cut==1 | Shave==1,taskcat1:=1]
cosmo_class[`Color/Bleach`==1 | `Highlight/Balayage`==1 | `Wash/Shampoo`==1  ,taskcat2:=1]
cosmo_class[Extensions==1, taskcat3:=1]
cosmo_class[ Blowdry==1  |Style==1 | `Other Treatment`==1  ,taskcat4:=1]
cosmo_class[ (`Admin/Consult`==1 & main_cat==1) , taskcat5:=1]


for(var in colnames(cosmo_class)[colnames(cosmo_class) %like% "taskcat"]){
  cosmo_class[,(var):=ifelse(is.na(get(var)), 0, get(var))]
}
cosmo_class[, count_cat:=rowSums(.SD), .SDcols=colnames(cosmo_class)[colnames(cosmo_class) %like% "taskcat"]]
## nail.spa/other category/ 
cosmo_class[ ,taskcat6:= as.numeric(count_cat==0)]

cosmo_class<-cosmo_class[,.SD,.SDcols=c("count_cat","Male","Female","Child","raw_id", "Service Description",colnames(cosmo_class)[colnames(cosmo_class) %like% "taskcat"]) ]

saveRDS(cosmo_class, "data/classified_descriptions.rds")
